telegram_token: "6373203900:AAE9MFdq6LplpWQFgCmISPqA_9duGumPmFM"
openai_api_key: "104b8b32c83643be85e905f1787b2227"
openai_api_url: "https://chatgpt.connect.siemens.cloud"
use_chatgpt_api: true
allowed_telegram_usernames: ["zvalley"]  # if empty, the bot is available to anyone. pass a username string to allow it and/or user ids as positive integers and/or channel ids as negative integers
new_dialog_timeout: 600  # new dialog starts after timeout (in seconds)
return_n_generated_images: 1
n_chat_modes_per_page: 5
enable_message_streaming: true  # if set, messages will be shown to user word-by-word

# prices
chatgpt_price_per_1000_tokens: 0.002
gpt_price_per_1000_tokens: 0.02
whisper_price_per_1_min: 0.006